
CXX := g++
FLAGS := -g
HEADER := -I.
SRC := $(wildcard source/*.cpp)
SRC += $(wildcard source/*/*.cpp)
LIB := ./libs/libddjson.so
BIN := demo.bin

all: $(LIB) $(BIN)

$(LIB): $(SRC) header/*.hpp
	mkdir -p libs
	$(CXX) $(FLAGS) $(HEADER) -fPIC -c $(SRC)
	mv *.o libs
	$(CXX) $(FLAGS) $(HEADER) -shared -o $(LIB) ./libs/*.o

$(BIN): demo.cpp $(LIB)
	$(CXX) $(FLAGS) $(HEADER) -L./libs -o $(BIN) demo.cpp -lddjson

clean:
	rm -f *.exe.* *.exe *.gch $(BIN)
	rm -f ./libs/*.so ./libs/*.o
