
CXX := g++
CXXFLAGS := -g
HEADER := -Iheader
LIB := ./libs/libddjson.so
BIN := demo.bin

all: $(LIB) $(BIN)

$(LIB): source/*.cpp source/*/*.cpp header/*.h
	mkdir -p libs
	$(CXX) $(CXXFLAGS) $(HEADER) -fPIC -c source/*.cpp source/*/*.cpp
	mv *.o libs
	$(CXX) $(CXXFLAGS) $(HEADER) -shared -o $(LIB) ./libs/*.o

$(BIN): demo.cpp $(LIB)
	$(CXX) $(CXXFLAGS) $(HEADER) -L./libs -o $(BIN) demo.cpp -lddjson

clean:
	rm -f *.exe.* *.exe *.gch $(BIN)
	rm -f ./libs/*.so ./libs/*.o
