
CXX := g++
FLAGS := -g
INCLUDES := -Iheader
LIBS := -lddjson -lCatch2Main -lCatch2
SRC := $(wildcard tests/*.cpp)
BIN := tests.bin

all: $(SRC)
	make -f Makefile.src
	$(CXX) $(FLAGS) $(INCLUDES) -L./libs -o $(BIN) $(SRC) $(LIBS)

clean:
	rm -f $(BIN)
