
CXX := g++
CXXFLAGS := -g
HEADER := -Iheader

all: ddjson.so demo.bin

ddjson.so: source/*.cpp source/*/*.cpp header/*.h
	mkdir -p libs
	$(CXX) $(CXXFLAGS) $(HEADER) -fPIC -c source/*.cpp source/*/*.cpp
	mv *.o libs
	$(CXX) $(CXXFLAGS) $(HEADER) -shared -o ./libs/libddjson.so ./libs/*.o

demo.bin: demo.cpp ./libs/libddjson.so
	$(CXX) $(CXXFLAGS) $(HEADER) -L./libs -o demo.bin demo.cpp -lddjson

clean:
	rm -f *.exe.* *.exe *.gch demo.bin
	rm -f ./libs/*.so ./libs/*.o
